### ISSUE TITLE
Add option to disable for specific filetypes or paths

### ISSUE THREAD

**Issue by WybeBosch** [geriyoco/vscode-image-gallery#127]
Hey there, really enjoying the extension so far. 
Only issue i come across is that i can no longer open the raw HTML of .svg files since installing the extension. 

Probably because the extension tries to load them as images.

Is this something that could be fixed by adding an option to disable for certain file extensions perhaps?

**Comment by WybeBosch** [comment]
Ah i see that in your first screenshot there is also an option named "Configure default editor for '*.svg'
That worked out perfectly, and makes it so you do not have to add in an option in the extension :) 

For other people looking for the solution
```json
	"workbench.editorAssociations": {
		"*.svg": "default"
	}
```

**Comment by fanurs** [comment]
Good to know! I will close this issue then. Thanks and have a nice day.
