### ISSUE TITLE
Tooltips on hover at gallery

### ISSUE THREAD

**Issue by alex2chan** [geriyoco/vscode-image-gallery#27]
tooltips will have description such as image name, dimensions, size, date created/modified, etc..

**Comment by fanurs** [comment]
That could make hovering annoying, if I am not interested in those info (most of the time).

Wouldn't that better suited to put in Viewer?

**Comment by alex2chan** [comment]
a delay on hover

**Comment by fanurs** [comment]
@alex2chan See #28

**Comment by fanurs** [comment]
File stats can easily be enquired as demonstrated below:
https://github.com/geriyoco/vscode-image-gallery/blob/4f8cce0fef34bcb9d6083ac9e132f2bfb872b915/src/gallery.ts#L143-L146

The question now is: How to send the inquired information back to [`media/gallery.js` ](https://github.com/geriyoco/vscode-image-gallery/blob/4f8cce0fef34bcb9d6083ac9e132f2bfb872b915/media/gallery.js) to update the tooltip's content?

Reference: https://code.visualstudio.com/api/references/vscode-api#FileStat
