### ISSUE TITLE
Display filename as tab title

### ISSUE THREAD

**Issue by Ying-Kang** [geriyoco/vscode-image-gallery#48]
image gallary is a wonderful job for image browse situation especially when using vscode for remote

however, when i check images in gallary, i want to know which image name attach to it and gallary gives no choice for select

![image](https://user-images.githubusercontent.com/32356801/166111626-c678bbca-b303-496f-95f6-11c942001a5d.png)

which made it a little bit difficult to figure out the especilly wrong image i focus on

i hope it can be taken into account for updating asap

thx

**Comment by fanurs** [comment]
@Ying-Kang Feature added since `v0.2.3`.
