### ISSUE TITLE
Sort gallery images by filenames

### ISSUE THREAD

**Issue by Ying-Kang** [geriyoco/vscode-image-gallery#59]
image gallary can view image in a better way than vscode

however, maybe it could be optimize to re-organize the filename via natural filename order for convenience especilly in scientific statistics situation
![image](https://user-images.githubusercontent.com/32356801/168411419-1ca26052-b393-4c42-b775-6c2b43365448.png)

it maybe a easy job to fix as far as i'm concerned

and hope it could be update asap

thx

**Comment by fanurs** [comment]
@Ying-Kang Available since `v0.2.5`. See https://github.com/geriyoco/vscode-image-gallery/pull/60#issuecomment-1126789552 for more configurables.
