### ISSUE TITLE
Keyword Optimization does not take subtitle keywords 

### ISSUE THREAD

**Issue by AnnaG0mez** [geriyoco/vscode-image-gallery#91]
Two separate users have reached out regarding not being able to add subtitles and keywords in Keyword Optimization.
**App Intelligence > ASO > Keyword Optimization**

Users: 
[vladimirshourov@gmail.com](mailto:vladimirshourov@gmail.com)
[mangekeyosharingan6@gmail.com](mailto:mangekeyosharingan6@gmail.com)

When adding keywords for subtitle after hitting enter nothing populates after re-creating with several different keywords. 

<img width="1382" alt="Screen Shot 2022-08-17 at 4 55 25 PM" src="https://user-images.githubusercontent.com/109562487/185241538-0f6110da-cb98-4904-ac4c-2620beb2bc0d.png">

After pressing enter:

<img width="398" alt="Screen Shot 2022-08-17 at 4 55 56 PM" src="https://user-images.githubusercontent.com/109562487/185242214-8e830a50-61ff-4213-a56e-4d7d056cb8a8.png">

**Comment by fanurs** [comment]
Hi @AnnaG0mez 

I am not entirely sure what is this issue about. Is it related to this repo, "Image Gallery", an extension on VS Code?
